import { LocaleMessages } from './zh';

const en: LocaleMessages = {
  // App
  app: {
    brand: 'BIMVision',
    pro: 'PRO',
    openModel: 'Open BIM Model',
    supportFormat: 'Supports IFC format',
    dragHint: 'Click "Load" in toolbar to import, or simply',
    dragHere: 'drag & drop',
    dragEnd: 'here',
    releaseToLoad: 'Release to load model',
    supportedFormat: 'Supports IFC format',
    isolationBanner: 'Isolation mode active — click to exit',
    clearScene: 'Clear Current Scene',
    clearSceneDesc: 'This will remove all loaded models and measurement records. This action cannot be undone.',
    confirmClear: 'Clear Scene',
    cancel: 'Cancel',
    loading: 'Loading file…',
    parsing: 'Parsing model data…',
    buildingGeometry: 'Building geometry and property index',
    uploadingSample: 'Loading sample model...',
    downloadSampleFailed: 'Failed to download sample model. Please check network!',
    activeModels: 'active models',
    unnamedModel: 'Unnamed Model',
  },

  // Toolbar
  toolbar: {
    load: 'Load',
    sample: 'Samples',
    selectSample: 'Select Sample',
    model: 'Model',
    properties: 'Properties',
    annotations: 'Annotations',
    report: 'Report',
    walk: 'Walk',
    measure: 'Measure',
    section: 'Section',
    fit: 'Fit',
    view: 'View',
    clear: 'Clear',
    distance: 'Distance',
    angle: 'Angle',
    coordinate: 'Coordinate',
    measureList: 'Measurements',
    clearAllMeasure: 'Clear All',
    resetSection: 'Reset & Disable All Planes',
  },

  // Views
  views: {
    top: 'Top View',
    bottom: 'Bottom View',
    front: 'Front View',
    back: 'Back View',
    left: 'Left View',
    right: 'Right View',
    isoNE: 'NE Isometric',
    isoNW: 'NW Isometric',
    isoSE: 'SE Isometric',
    isoSW: 'SW Isometric',
    orthographic: 'Orthographic',
    isometric: 'Isometric',
  },

  // Samples
  samples: {
    structureModel: 'Structure Model (0.7MB)',
    ledScreen: 'LED Screen (5.2MB)',
    energyTower: 'Energy Tower (10.6MB)',
    wellnessCenter: 'Wellness Center (21.3MB)',
  },

  // Measurement Panel
  measurement: {
    title: 'Measurements',
    empty: 'No measurements yet',
    emptyDesc: 'Select a measurement tool from the toolbar and click on model surfaces to measure.',
    panelTitle: 'Measurement Results',
    clearAll: 'Clear All Measurements',
    exportReport: 'Export HTML Report (with snapshot)',
    deleteSingle: 'Delete measurement',
    locateHint: 'Double-click to locate this measurement',
    distance: 'Distance',
    angle: 'Angle',
    coordinate: 'Coordinate',
  },

  // Model Tree
  modelTree: {
    title: 'Model Tree',
  },

  // Properties
  properties: {
    title: 'Properties',
  },

  // BCF
  bcf: {
    title: 'Viewpoints & Annotations',
  },

  // Report
  report: {
    title: 'Quantity Report',
  },

  // Tips
  tips: {
    clickStart: 'Click start point',
    clickEnd: 'Click end point',
    clickVertex: 'Click vertex',
    clickNext: 'Click next point (double-click to finish)',
    clickCorner1: 'Click corner 1',
    clickCorner2: 'Click corner 2',
    clickAnyPoint: 'Click any point for coordinates',
  },

  // Theme
  theme: {
    switchToLight: 'Switch to Light Theme',
    switchToDark: 'Switch to Dark Theme',
  },

  // Screenshot
  screenshot: {
    save: 'Save Screenshot',
  },

  // About
  about: {
    title: 'About & Help',
  },

  // Report export
  reportExport: {
    title: 'BIMVision Pro Measurement & Analysis Report',
    measureRecords: 'Measurement Records',
    snapshot: 'Viewpoint Snapshot',
    printPdf: 'Print Report / Export PDF',
    footer: 'This report is auto-generated by BIMVision Pro. Copyright © 2026.',
    index: 'No.',
    type: 'Type',
    value: 'Value',
    fileName: 'File Name',
    exportTime: 'Export Time',
    reportNo: 'Report No.',
  },
};

export default en;
